 Class = require 'class'
 sti = require 'lib.sti'
 bump = require 'lib.bump'
 camara = require 'lib.camera'
require  'jugador'
require  'enemigo'
require  'estado'
require  'estadojugar'
require 'estadotitulo'
require 'maquinaestado'
require 'estadoDerota' 
   